# Generated by Django 4.0.4 on 2022-05-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='anime_imgs'),
        ),
    ]
