# Generated by Django 4.0.4 on 2022-05-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='title',
            new_name='name',
        ),
    ]
