# Generated by Django 4.0.4 on 2022-06-04 20:17

from django.db import migrations, models
import numpy


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_alter_anime_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watched',
            field=models.ManyToManyField(default=numpy.empty, related_name='watched', to='anime.anime'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='wtwatch',
            field=models.ManyToManyField(default=numpy.empty, related_name='wtwatch', to='anime.anime'),
        ),
    ]
