# Generated by Django 4.0.4 on 2022-06-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_alter_watchlist_watched_alter_watchlist_wtwatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watched', to='anime.anime'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='wtwatch',
            field=models.ManyToManyField(blank=True, related_name='wtwatch', to='anime.anime'),
        ),
    ]
