# Generated by Django 4.0.4 on 2022-06-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50, unique=True), null=True, unique=True),
        ),
    ]
