# Generated by Django 4.0.4 on 2022-06-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_alter_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
