# Generated by Django 4.0.4 on 2022-06-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_anime_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
