# Generated by Django 4.0.4 on 2022-06-12 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0016_alter_anime_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=6)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3000)])),
            ],
        ),
    ]
