# Generated by Django 4.0.4 on 2022-06-12 18:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0017_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='anime.season'),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('FINISHED', 'Finished')], default='ONGOING', max_length=8),
        ),
        migrations.AddField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('ONA', 'ONA'), ('TV', 'TV'), ('SPECIAL', 'Special'), ('MOVIE', 'Movie'), ('OVA', 'OVA')], default='TV', max_length=7),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
