# Generated by Django 4.0.4 on 2022-06-12 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_anime_season_anime_status_anime_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
