# Generated by Django 4.0.4 on 2022-06-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0019_alter_season_season_alter_season_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('SPRING', 'Spring'), ('FALL', 'Fall'), ('WINTER', 'Winter')], default='SUMMER', max_length=6),
        ),
    ]
