# Generated by Django 4.0.4 on 2022-06-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0020_alter_season_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
