# Generated by Django 4.0.4 on 2022-06-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0022_alter_anime_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='anime.season'),
        ),
    ]
