# Generated by Django 4.0.4 on 2022-06-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0023_alter_anime_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current',
            field=models.CharField(choices=[('CURRENT', 'Current'), ('PAST', 'Past')], default='PAST', max_length=7),
        ),
    ]
