# Generated by Django 4.0.4 on 2022-06-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0026_alter_anime_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('SPRING', 'Spring'), ('FALL', 'Fall'), ('WINTER', 'Winter'), ('UNDEFINED', 'Undefined')], default='SUMMER', max_length=9),
        ),
    ]
