# Generated by Django 4.0.4 on 2022-06-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0032_alter_anime_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
